"""empty message

Revision ID: 26dd1fc67981
Revises: 1008d88a5960
Create Date: 2025-01-02 21:22:54.959639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dd1fc67981'
down_revision = '1008d88a5960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_training', sa.Column('workout_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_training', 'workout_type')
    # ### end Alembic commands ###
