"""app personal training

Revision ID: 291f1ab5bc83
Revises: e68e08106619
Create Date: 2024-12-24 18:50:30.141999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291f1ab5bc83'
down_revision = 'e68e08106619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaltraining',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_type_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coach.id'], ),
    sa.ForeignKeyConstraint(['day_of_week_id'], ['day_of_week.id'], ),
    sa.ForeignKeyConstraint(['exercise_type_id'], ['exercise_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personaltraining')
    # ### end Alembic commands ###
