"""empty message

Revision ID: 29347aa0e926
Revises: 48ce9e391f1b
Create Date: 2025-01-13 18:50:33.510793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29347aa0e926'
down_revision = '48ce9e391f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_unique_booking', 'booking', ['user_id', 'workout_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_booking', table_name='booking')
    # ### end Alembic commands ###
