"""Update teacher

Revision ID: e68e08106619
Revises: 79dd3e10b0b5
Create Date: 2024-12-24 17:39:34.290231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68e08106619'
down_revision = '79dd3e10b0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('photo', sa.String(length=255), nullable=True))
    op.add_column('coach', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach', 'description')
    op.drop_column('coach', 'photo')
    # ### end Alembic commands ###
