"""empty message

Revision ID: e8fe1ee38201
Revises: 29347aa0e926
Create Date: 2025-01-13 19:20:21.288661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fe1ee38201'
down_revision = '29347aa0e926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_booking', table_name='booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_unique_booking', 'booking', ['user_id', 'workout_id'], unique=1)
    # ### end Alembic commands ###
